# Generated by Django 4.2.2 on 2023-07-25 02:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pdv', '0003_prescription_number_prescription_sale_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='sale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='pdv.sale'),
        ),
    ]
