# Generated by Django 4.2.2 on 2024-01-04 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdv', '0005_prescriptionpartial_prescriptiontotal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Descripcion'),
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Descripcion'),
        ),
    ]
