# Generated by Django 4.2.2 on 2024-01-15 05:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pdv', '0007_medicalconsultation'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalConsultationReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Fecha')),
                ('total', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Venta total')),
            ],
        ),
        migrations.CreateModel(
            name='SaleReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Fecha')),
                ('total_sold', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Venta total')),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Costo total')),
            ],
        ),
        migrations.CreateModel(
            name='ArticleSaleReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Fecha')),
                ('quantity', models.IntegerField(verbose_name='Cantidad vendida')),
                ('total_sold', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Venta total')),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Costo total')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='pdv.article')),
            ],
        ),
    ]
