# Generated by Django 4.2 on 2024-12-31 03:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdv', '0009_salereport_sale_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='name',
            field=models.CharField(max_length=256, unique=True, validators=[django.core.validators.RegexValidator('\\S+', 'El nombre del articulo no puede ser solamente espacios', 'whitespace', None, 0)], verbose_name='Nombre del articulo'),
        ),
        migrations.AlterField(
            model_name='medic',
            name='name',
            field=models.CharField(max_length=256, validators=[django.core.validators.RegexValidator("^[A-Za-zÀ-ÿ']{2,}[A-Za-zÀ-ÿ' ]*$", 'Nombre invalido', 'invalid')], verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='medic',
            name='sur_name_a',
            field=models.CharField(max_length=256, validators=[django.core.validators.RegexValidator("^[A-Za-zÀ-ÿ']{2,}[A-Za-zÀ-ÿ' ]*$", 'Nombre invalido', 'invalid')], verbose_name='Apellido Paterno'),
        ),
        migrations.AlterField(
            model_name='medic',
            name='sur_name_b',
            field=models.CharField(max_length=256, null=True, validators=[django.core.validators.RegexValidator("^[A-Za-zÀ-ÿ']{2,}[A-Za-zÀ-ÿ' ]*$", 'Nombre invalido', 'invalid')], verbose_name='Apellido Materno'),
        ),
    ]
