# Generated by Django 4.2 on 2025-01-02 04:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pdv', '0010_alter_article_name_alter_medic_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ControlledArticleInOut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Fecha')),
                ('delta', models.IntegerField(verbose_name='Cambio en cantidad')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='pdv.article')),
            ],
        ),
    ]
