# Generated by Django 4.2.1 on 2023-06-03 03:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, unique=True)),
                ('description', models.TextField(null=True)),
                ('barcode', models.CharField(max_length=48, unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('quantity', models.IntegerField(default=1)),
                ('min_quantity', models.IntegerField(default=1)),
                ('has_iva', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('description', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Medic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('sur_name_a', models.CharField(max_length=256)),
                ('sur_name_b', models.CharField(max_length=256, null=True)),
                ('address', models.TextField()),
                ('cedula', models.IntegerField(unique=True)),
                ('ssa', models.IntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('amount_payed', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='ExpiryDate',
            fields=[
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='pdv.article')),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='SingleSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='pdv.article')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='pdv.sale')),
            ],
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medic', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='pdv.medic')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='pdv.singlesale')),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='pdv.category'),
        ),
    ]
