# Generated by Django 4.2.2 on 2023-07-24 04:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pdv', '0002_remove_prescription_sale_prescription_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='number',
            field=models.IntegerField(null=True, unique=True, verbose_name='Folio'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='sale',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='pdv.singlesale'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prescription',
            name='total',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='PrescriptionArticle',
        ),
    ]
