# Generated by Django 4.2.2 on 2024-01-04 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdv', '0006_alter_article_description_alter_category_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalConsultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Costo')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('date', models.DateField(verbose_name='Fecha')),
                ('is_consultation', models.BooleanField(verbose_name='Es consulta')),
            ],
        ),
    ]
