# Generated by Django 4.2.2 on 2024-01-15 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdv', '0008_medicalconsultationreport_salereport_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salereport',
            name='sale_count',
            field=models.IntegerField(default=0, verbose_name='Ventas realizadas'),
        ),
    ]
