# Generated by Django 4.2 on 2025-01-13 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdv', '0011_controlledarticleinout'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='controlled',
            field=models.BooleanField(default=False, verbose_name='Antibiotico'),
        ),
    ]
