# Generated by Django 4.2 on 2025-06-04 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pdv', '0013_article_deleted_at_article_restored_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='singlesale',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='pdv.article'),
        ),
    ]
