# Generated by Django 4.2 on 2025-06-04 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pdv', '0014_alter_singlesale_article'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controlledarticleinout',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='pdv.article'),
        ),
    ]
